# NUMPY LIBRARY 

### In Python by using numpy library we can do operations very fastly and the difference between and list is that list stores various data types where as numpy array stores same data type elements. 

###  we can do lot of advanced operations in numpy and it is used for scientific computing 

In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [9]:
a=np.array([[1,2,3],[5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [10]:
a.shape  #it displays rows and columns

(2, 3)

In [18]:
a=np.array([[[1,2,3],[5,6,7]],[[11,12,13],[14,15,17]]])
a

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[11, 12, 13],
        [14, 15, 17]]])

In [19]:
a.shape    #it displays layers,rows,columns

(2, 2, 3)

In [20]:
a.ndim

3

In [21]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b=np.linspace(1,2,9)
b


array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [41]:
a=np.zeros((2,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
a=np.ones((2,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
a=np.eye(2,3,dtype=int)
a

array([[1, 0, 0],
       [0, 1, 0]])

In [59]:
a=np.diag((1,2,3,4))
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [61]:
a=np.array([[1,2,3],[11,12,13]])    # Gives Transpose of the matrix
a.T

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

# ## SLICING OPERATIONS

In [25]:
a=np.arange(20)
a[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
b=np.arange(30)
b[4:23:2]


array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

# # UPDATING THE INFO IN NUMPY ARRAY 

In [29]:
a=np.array([2,34,787])
a

array([  2,  34, 787])

In [33]:
a[2]=100
a

array([  2,  34, 100])

# # Random OPerations

In [37]:
a=np.random.randint(2,20,6)  #start,end,values
a

array([11,  8, 17, 17,  5,  8])

In [39]:
a=np.random.rand(4)              #prints 4 floating values between 0 and 1
a      

array([0.9821177 , 0.82964322, 0.29616819, 0.25578606])

# # Array Operations

In [133]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [134]:
a-b

array([-3, -3, -3])

In [135]:
a*b

array([ 4, 10, 18])

In [136]:
a/b

array([0.25, 0.4 , 0.5 ])

In [137]:
a*2

array([2, 4, 6])

In [138]:
a+1

array([2, 3, 4])

In [139]:
a*a

array([1, 4, 9])

In [140]:
a>b

array([False, False, False])

In [141]:
(a>b).all()

False

In [142]:
np.array_equal(a,b)

False

In [144]:

np.insert(a, 2, b)

array([1, 2, 4, 5, 6, 3])

In [146]:
np.delete(a,1)

array([1, 3])

# Dimension shuffling

In [73]:
a=np.array([[4,5,6],[1,2,3]])     #FLATTENING
a.ravel()

array([4, 5, 6, 1, 2, 3])

In [74]:
a.shape

(2, 3)

In [78]:
a.reshape((3,2),order='F')

array([[4, 2],
       [1, 6],
       [5, 3]])

# Mathematical Operatiosn

In [118]:
a=np.array([[1,2,3],[3,4,5]])
a.sum(axis=1)

array([ 6, 12])

In [119]:
a.min()

1

In [120]:
a.max()

5

In [121]:
a=np.array([5,9,7])

a

array([5, 9, 7])

In [122]:
np.sort(a)

array([5, 7, 9])

In [123]:
a.std()

1.632993161855452

In [124]:
a.mean()

7.0

In [127]:
np.median(a)

7.0

## index operations

In [159]:
a=np.array([7,8,9])
np.where(a>8)

(array([2], dtype=int64),)

In [160]:
a[a>8]


array([9])

In [164]:
np.where(a>=8,a,0)

array([0, 8, 9])